name: angel3_doc
version: 6.0.0
description: Angel3 documentation
publish_to: none
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  angular: ^7.0.0
  angular_router: ^3.0.0
  angular_forms: ^4.0.0
  #angular_components: ^1.0.2
  #skawa_material_components: ^1.5.0
  firebase: ^9.0.2
  crypto: ^3.0.1
dev_dependencies:
  sass: ^1.44.0
  angular_test: ^4.0.0
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^3.2.1
  test: ^1.16.5
  sass_builder: ^2.1.3
  lints: ^1.0.0